apiVersion: apps/v1
kind: Deployment
metadata:
  name: saidemy-regapp
  labels:
     app: regapp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: regapp
  
  template:
    metadata:
      labels:
        app: regapp
    
    spec:
      containers:
      - name: regapp
        image: sharad150892/regapp
        imagePullPolicy: Always # always pull latest image
        ports:
        - containerPort: 8080
    
    
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
