apiVersion: v1
kind: Service
metadata:
  name: demo-service

spec:
  ports:
  - name: nginx-port
    port: 80
    targetPort: 80  #container's expose port

  selector:
    app: demo-app

  type: LoadBalancer



